---

- name: Push base config
  hosts: all

  tasks:
    - name: push base config
      napalm_install_config: 
            hostname="{{ ansible_host }}"
            username="{{ ansible_user }}"
            password="{{ ansible_pass }}"
            dev_os=ios
            config_file={{config_dir}}/{{hostname}}/baseconfig.txt
            commit_changes=True
            replace_config=False
            diff_file={{config_dir}}/{{hostname}}/baseconfig.diff