---

- name: diff base config
  hosts: all

  tasks:
    - name: push base config
      napalm_install_config: 
            hostname="{{ ansible_host }}"
            username="{{ ansible_user }}"
            password="{{ ansible_pass }}"
            dev_os=ios
            config_file={{config_dir}}/{{hostname}}/baseconfig.txt
            commit_changes=False
            replace_config=True
            diff_file={{config_dir}}/{{hostname}}/baseconfig.diff