---
- name: Get routing table
  gather_facts: no
  hosts: cisco_devices
  tasks:
    - name: Show routing table
      ios_command:
        provider: "{{ provider }}"
        commands:
          - show ip route
      register: info
    - debug: var=info.stdout_lines
